### PR TITLE
AccessibleEditor

### PR DESCRIPTION
**Pull request by Flameborn**
This is just an initial commit, not ready to merge yet.

* Add Editor to the _settings_ screen, via a user.Editor field
* 3 editor types: _Default_, _Minimalistic_ (Accessible), and _Minimalistic, without Javascript_ (just a textarea, no JS)

This implementation uses [Showdown](https://github.com/showdownjs/showdown) and [Countable](https://github.com/RadLikeWhoa/Countable), both under MIT.

The templates will probably need some visual adjustment.

I am currently investigating why an _oninput_ event will not fire on the MDE textarea.

### CODE REVIEW

**Comment by Flameborn** [comment]
This should be ready for a review, and for a possible merge.

I'm not entirely satisfied with the elegance of this, but it definitely works, adding new editors should be also quite easy.

**Comment by recoilme** [comment]
check this please 
https://github.com/recoilme/tgram/blob/master/routers/routers.go#L505
incrybmde has one \r\n for new line (classical markdown has \n\n i think)
it's ok for the new editor? how does it work with images? all ok?

**Comment by recoilme** [comment]
I am underwater right now, hope to merge it tomorrow

**Comment by Flameborn** [comment]
I've resolved the conflict from Master.

The editor is a standard textarea, so unless it has newline issues, things should work fine, at least they look all right in the live preview. The two divs, housing the stats and the live preview might be misaligned though.

Images are also handled by Typegram, since the form will post Markdown, unless you wish to receive HTML as the article body, which we can do easily.

**Comment by Flameborn** [comment]
> no test for unregistered user
> 
You are right. I could check for the path here. The problem is that the _Editor_ field is in a global hook, as you said, and I would rather not get the user struct for every request. Typegram, however, includes the editor everywhere, even if you do not use it, which is also not great. The only places where we should include code related to the editor are the _settings_, _article_ and _articleEdit_ pages.

> comments use incrybmde - not tested, not implemented
> 
Oops, I think I forgot to commit _article.html_ It is definitely using the minimalistic editor here.

> looks ugly
> 
I think we can fix this via CSS.

> add disable javascript - it will be the global option.
> 
_Disable javascript_ is a nice option, but I think Markdown definitely needs a preview, especially for the average user, who will probably have javascript enabled.

It could be frustrating that you only catch a mistake when you click submit, view your article and then you have to edit again to fix it.

I am not against disabling javascript, but I don’t think that disabling javascript would replace this in features.

As I have mentioned earlier, I am not happy with the state of this patch, it definitely needs optimisation, but I think we can do it. Visually impaired users will be able to use an accessible editor with most of the features in tact, while other editors can be implemented easier, if someone chooses to. For example CK Editor, etc.

**Comment by recoilme** [comment]
i created branch https://github.com/recoilme/tgram/tree/editor
for playing with alternative editors (with some fixes) if you want to continue to play with it
But right now it looks absolutely not accessible for release, sorry for that(

And i added nojavascript option in the main branch, as some solution for visually impaired users and users who dont like javascript

They may use classic textarea now

I do not think that the possibility of previewing is so important but if you want to make it it should look beautiful and work correctly. For me, it's better not to do anything than do it badly. I'm sorry that I did not include your code, Robert in the release (It's too bad, but I do not have time right now and I'm not so good at the front end to try to bring this feature to the release. Maybe return to it later

**Pull request merged**
