### PR TITLE
Refactored some internal parameters, such as Admin, Site Name, to env…

### PR DESCRIPTION
**Pull request by Flameborn**
Converted parameters to environmental variables.

### CODE REVIEW

**Comment by recoilme** [comment]
@Flameborn  do you have an account on product hunt?
i want add you to makers
https://www.producthunt.com/my/upcoming/typegram

**Comment by Flameborn** [comment]
Sure, take your time 😀

**Comment by Flameborn** [comment]
Yes, as of a few minutes ago: https://www.producthunt.com/@erion

Adding me is most appreciated!

**Comment by recoilme** [comment]
@Flameborn you are welcome!

**Comment by recoilme** [comment]
Erion, may you please add some initialization of config with default values before loading from *env?
Right now typegram works without typegram.env with some default values..
except this - it's looks good, thank you!

**Comment by Flameborn** [comment]
I might have missed a default value, but the template should use default values if the env values are missing. Title, description, etc.

Which field needs a default value at the moment?

**Comment by recoilme** [comment]
in menu or policy for example, i prefer don't check in every template - but init all values before use  - one time in one place

on other hand - it's very minor change, i may accept and implement it later, as you wish?

**Comment by Flameborn** [comment]
Ah, I see what you mean. So you prefer to initialise items in source, rather than leave it for the template writers. That's reasonable, of course, and you are right, it's an easy change. I'm going to push it in a few minutes.

**Comment by recoilme** [comment]
Thank you! There is no reason to hurry, have a good weekend!

**Comment by Flameborn** [comment]
I have just pushed the init commit with the default Typegram parameters. Please let me know if anything else is missing.

**Comment by recoilme** [comment]
Lgtm!

**Pull request merged**
